[project]
name = "ask-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.7.5",
    "aiohttp>=3.8.0",
    "exa-py>=1.14.17",
    "fastapi>=0.116.1",
    "pymongo>=4.13.2",
    "uvicorn>=0.32.1",
]
